require "user.basic"
require "user.plugins"
require "user.keybindings"
require "user.which-key"
require "user.colorschemes.ayu"
require "user.dashboard"
require "user.impatient"
require "user.autocommands"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.navic"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.illuminate"
require "user.indentline"
require "user.lsp"
require "user.dap"
require "user.zen-mode"
require "user.jaq"
require "user.neotest"
require "user.hop"
require "user.cheatsheet"
require "user.go"
require "user.cmp"

if vim.fn.exists("g:neovide") then
  vim.opt.guifont = { "JetBrainsMonoNL Nerd Font Mono", "h16.5" }
end
